---
# Updates Red Hat Like
- name: Update Sstem Red Hat
  yum: name=* state=latest security=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'


# Updates Debian Like
- name: Update System Debian
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'ubuntu'


...
