---
# Gerenciamento de pacotes e atualizacao do SO
- name: Atualizacao do Sistema Operacional
  yum: name=* state=latest update_cache=yes
- name: Instalacao de pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - vim
      - nmap
      - tree

# Configuracao do Timezone
- name: Configurando o Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes


...
