---
# Gerenciamento de pacotes e atualizacao do SO
- name: Atualizacao do Sistema Operacional
  yum: name=* state=latest update_cache=yes
- name: Instalacao de pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - vim
      - nmap
      - tree

# Configuracao do Timezone
- name: Configurando o Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# Copia de arquivos
- name: copiando arquivo de backup
  copy: src=backup.tar.gz dest=/tmp

- name: copiando um template
  template: src=motd dest=/etc/motd force=yes owner=root group=root

# Instalacao do Apache
- name: instalacao do apache
  yum: name=httpd state=latest
  notify: Restart apache

...
